# Generated by Django 4.1 on 2025-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografica',
            new_name='Fotografia',
        ),
    ]
